export const SYSTEM_CONFIG_CATEGORY = {
  GENERAL: 'GENERAL',
  FEATURE_FLAG: 'FEATURE_FLAG',
  INTEGRATION: 'INTEGRATION',
  SECURITY: 'SECURITY',
} as const;

export type SystemConfigCategory = keyof typeof SYSTEM_CONFIG_CATEGORY;

export const FEATURE_FLAGS = {
  REGISTRATION_ENABLED: 'feature.registration.enabled',
  NOTIFICATIONS_ENABLED: 'feature.notifications.enabled',
  WEBHOOKS_ENABLED: 'feature.webhooks.enabled',
  AI_ENABLED: 'feature.ai.enabled',
  SOCIAL_LOGIN_ENABLED: 'feature.social_login.enabled',
  DISCORD_LOGIN_ENABLED: 'feature.discord_login.enabled',
  DISCORD_GATED_DOWNLOAD: 'feature.discord_gated_download.enabled',
  THEME_ANNOUNCEMENT_WEBHOOK: 'feature.theme_announcement_webhook.enabled',
  TIER_DOWNLOAD_QUOTA: 'feature.tier_download_quota.enabled',
  CREATOR_STUDIO_ENABLED: 'feature.creator_studio.enabled',
  COLLECTIONS_ENABLED: 'feature.collections.enabled',
  KEYBOARD_LIKES_ENABLED: 'feature.keyboard_likes.enabled',
  CRON_SCHEDULER_ENABLED: 'feature.cron_scheduler.enabled',
  DISCORD_IMPORT_ENABLED: 'feature.discord_import.enabled',
  AI_IMPORT_ENABLED: 'feature.ai_import.enabled',
} as const;

export type FeatureFlagKey = (typeof FEATURE_FLAGS)[keyof typeof FEATURE_FLAGS];

export const DEFAULT_SYSTEM_CONFIGS = [
  {
    key: 'app.name',
    value: 'KeyboardHub',
    description: 'Tên nền tảng hiển thị công khai',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'app.support_email',
    value: 'support@keyboardhub.local',
    description: 'Email liên hệ hỗ trợ khách hàng',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'app.timezone',
    value: 'Asia/Ho_Chi_Minh',
    description: 'Múi giờ chuẩn mặc định của hệ thống (UTC+7 / Asia/Ho_Chi_Minh)',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'app.locale',
    value: 'vi-VN',
    description: 'Ngôn ngữ và định dạng vùng mặc định (Tiếng Việt)',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'discord.invite_url',
    value: 'https://discord.gg/DVu3TTv3',
    description: 'Đường dẫn liên kết mời gia nhập Discord Server cộng đồng',
    category: SYSTEM_CONFIG_CATEGORY.INTEGRATION,
    isPublic: true,
  },
  {
    key: 'discord.vip_role_ids',
    value: ['123456789012345678'],
    description: 'Danh sách Discord Role IDs được hưởng đặc quyền (tải không giới hạn)',
    category: SYSTEM_CONFIG_CATEGORY.INTEGRATION,
    isPublic: false,
  },
  {
    key: 'keyboard.download_rate_limit_per_minute',
    value: 5,
    description: 'Giới hạn số lượt yêu cầu tải theme tối đa trên 1 phút cho mỗi người dùng',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: false,
  },
  {
    key: 'keyboard.default_page_size',
    value: 20,
    description: 'Số lượng theme mặc định hiển thị trên mỗi trang danh mục',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'keyboard.tier_free_download_limit',
    value: 10,
    description: 'Số lượng theme tối đa mà Free User (chưa tham gia Discord Server) được phép tải',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'keyboard.tier_member_download_limit',
    value: 50,
    description: 'Số lượng theme tối đa mà Thành viên Discord Server được phép tải',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'keyboard.quota_reset_cycle',
    value: 'MONTHLY',
    description: 'Chu kỳ tự động làm mới hạn mức tải về (MONTHLY: hàng tháng, LIFETIME: trọn đời)',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },
  {
    key: 'collections.max_themes_per_collection',
    value: 100,
    description: 'Số lượng theme tối đa được gán vào một bộ sưu tập',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: true,
  },

  {
    key: FEATURE_FLAGS.REGISTRATION_ENABLED,
    value: true,
    description: 'Cho phép người dùng mới đăng ký tài khoản tự do',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.NOTIFICATIONS_ENABLED,
    value: true,
    description: 'Bật hệ thống gửi thông báo và email tự động',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: FEATURE_FLAGS.WEBHOOKS_ENABLED,
    value: true,
    description: 'Bật hạ tầng Webhook dispatching và retry worker',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: FEATURE_FLAGS.AI_ENABLED,
    value: false,
    description: 'Bật các tính năng và API hỗ trợ AI',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.SOCIAL_LOGIN_ENABLED,
    value: true,
    description: 'Bật tính năng đăng nhập mạng xã hội (Google, Zalo)',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.DISCORD_LOGIN_ENABLED,
    value: true,
    description: 'Bật tính năng đăng nhập bằng tài khoản Discord',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.DISCORD_GATED_DOWNLOAD,
    value: true,
    description: 'Bật cơ chế kiểm tra thành viên Discord Server và Role trước khi cấp quyền tải theme',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.THEME_ANNOUNCEMENT_WEBHOOK,
    value: true,
    description: 'Tự động gửi thông báo Rich Embed lên Discord Server khi theme mới được phát hành',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: FEATURE_FLAGS.CREATOR_STUDIO_ENABLED,
    value: true,
    description: 'Bật tính năng Creator Studio cho phép người sáng tạo quản lý theme và số liệu thống kê',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.COLLECTIONS_ENABLED,
    value: true,
    description: 'Bật tính năng Khám phá và Tạo bộ sưu tập',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.KEYBOARD_LIKES_ENABLED,
    value: true,
    description: 'Bật tính năng Thả tim và Lưu theme yêu thích',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: true,
  },
  {
    key: FEATURE_FLAGS.CRON_SCHEDULER_ENABLED,
    value: true,
    description: 'Bật hạ tầng chạy tự động ngầm của toàn bộ hệ thống Cron Jobs & BullMQ Scheduler',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: FEATURE_FLAGS.DISCORD_IMPORT_ENABLED,
    value: false,
    description: 'Bật hệ thống nhập liệu từ Discord Thread qua Discord Bot',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: FEATURE_FLAGS.AI_IMPORT_ENABLED,
    value: false,
    description: 'Bật AI Worker xử lý phân tích, dịch tên và phân loại keyboard từ Discord Import',
    category: SYSTEM_CONFIG_CATEGORY.FEATURE_FLAG,
    isPublic: false,
  },
  {
    key: 'import.ai_confidence_threshold',
    value: 0.9,
    description: 'Ngưỡng độ tin cậy AI tối thiểu (0-1) để một Draft được coi là Bulk Approve candidate',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: false,
  },
  {
    key: 'import.bulk_approve_max',
    value: 50,
    description: 'Số lượng Import Job tối đa được phép duyệt cùng lúc trong một thao tác Bulk Approve',
    category: SYSTEM_CONFIG_CATEGORY.GENERAL,
    isPublic: false,
  },
] as const;

export const SYSTEM_CONFIG_PUBSUB_CHANNEL = 'system_config:events';

